/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testing.old.style.analysis;

public class App {
    public String getGreeting() {
        return "Hello there world. + 1";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
